version: "3.9"

services:
  api:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - template_pgdata:/var/lib/postgresql/data

volumes:
  template_pgdata:
