version: "3.9"

services:
  api:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
    command: sh -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
